# Generated by Django 5.0.7 on 2024-09-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_alter_resume_name_alter_resume_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_file', models.FileField(upload_to='templates/')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resume.resumetemplate'),
        ),
    ]
